### ISSUE TITLE
Ensure works outside Rails contexts / HTTP name error in Pry

### ISSUE THREAD

**Issue by phillmv** [appcanary/appcanary.rb#10]
```ruby
[8] pry(main)> Appcanary::Client.vulnerable?
NameError: uninitialized constant Appcanary::HTTP::Bundler
from /Users/phillmv/.gem/ruby/2.2.0/gems/appcanary-0.1.0/lib/appcanary/http.rb:12:in `ship_gemfile'
[9] pry(main)> wtf?
Exception: NameError: uninitialized constant Appcanary::HTTP::Bundler
--
0: /Users/phillmv/.gem/ruby/2.2.0/gems/appcanary-0.1.0/lib/appcanary/http.rb:12:in `ship_gemfile'
1: /Users/phillmv/.gem/ruby/2.2.0/gems/appcanary-0.1.0/lib/appcanary/assert.rb:28:in `check'
2: /Users/phillmv/.gem/ruby/2.2.0/gems/appcanary-0.1.0/lib/appcanary/assert.rb:14:in `vulnerable?'
3: /Users/phillmv/.gem/ruby/2.2.0/gems/appcanary-0.1.0/lib/appcanary/assert.rb:42:in `vulnerable?'
4: (pry):14:in `__pry__'
5: /Users/phillmv/.gem/ruby/2.2.0/gems/pry-0.10.3/lib/pry/pry_instance.rb:355:in `eval'
6: /Users/phillmv/.gem/ruby/2.2.0/gems/pry-0.10.3/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
7: /Users/phillmv/.gem/ruby/2.2.0/gems/pry-0.10.3/lib/pry/pry_instance.rb:323:in `handle_line'
8: /Users/phillmv/.gem/ruby/2.2.0/gems/pry-0.10.3/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
9: /Users/phillmv/.gem/ruby/2.2.0/gems/pry-0.10.3/lib/pry/pry_instance.rb:242:in `catch'
[10] pry(main)> Bundler
NameError: uninitialized constant Bundler
```

**Comment by j0ni** [comment]
I think this is the best we can do with this scenario:

```zsh
joni@ship j0ni/review-comments 0 rake build
appcanary 0.1.0 built to pkg/appcanary-0.1.0.gem.
joni@ship j0ni/review-comments 0 gem insta  pkg/appcanary-0.1.0.gem 
Successfully installed appcanary-0.1.0
Parsing documentation for appcanary-0.1.0
Installing ri documentation for appcanary-0.1.0
Done installing documentation for appcanary after 0 seconds
1 gem installed
joni@ship j0ni/review-comments 0 pry
[1] pry(main)> require "appcanary"
=> true
[2] pry(main)> Appcanary::Client.vunlerable?
NoMethodError: undefined method `vunlerable?' for Appcanary::Client:Class
Did you mean?  vulnerable?
from (pry):2:in `__pry__'
[3] pry(main)> Appcanary::Client.vulnerable?
Appcanary::ConfigurationError: No valid configuration found
Check out the following links for more information:
- https://github.com/appcanary/appcanary.rb
- https://appcanary.com/settings
from /home/joni/.gem/ruby/2.3.3/gems/appcanary-0.1.0/lib/appcanary/configuration.rb:108:in `rescue in block in resolved_config'
[4] pry(main)>
```
